((pawn "Pawn" "P" tokin #f 0 0 ((shortmove 2)))
(king "King" "K" #f #f 1 0 ((shortmove 1879)))
(lance "Lance" "L" white-horse #f 2 0 ((longmove 2)))
(silver-general "Silver General" "S" prom-silver-general #f 3 0 ((shortmove 1287)))
(gold-general "Gold General" "G" prom-gold-general #f 4 0 ((shortmove 599)))
(copper-general "Copper General" "C" prom-copper-general #f 5 0 ((shortmove 519)))
(bishop "Bishop" "B" prom-bishop #f 6 0 ((longmove 1285)))
(rook "Rook" "R" prom-rook #f 7 0 ((longmove 594)))
(blind-tiger "Blind Tiger" "BT" flying-stag #f 8 0 ((shortmove 1877)))
(dragon-horse "Dragon Horse" "DH" horned-falcon #f 9 0 ((shortmove 594) (longmove 1285)))
(dragon-king "Dragon King" "DK" soaring-eagle #f 10 0 ((shortmove 1285) (longmove 594)))
(drunk-elephant "Drunk Elephant" "DE" crown-prince #f 11 0 ((shortmove 1367)))
(ferocious-leopard "Ferocious Leopard" "FL" prom-ferocious-leopard #f 12 0 ((shortmove 1799)))
(free-king "Free King" "FK" #f #f 13 0 ((longmove 1879)))
(go-between "Go Between" "GB" prom-go-between #f 14 0 ((shortmove 514)))
(kylin "Kylin" "Ky" lion #f 15 0 ((shortmove 1285) (jumpmove 594)))
(phoenix "Phoenix" "Ph" free-king #f 16 0 ((shortmove 594) (jumpmove 1285)))
(lion "Lion" "Ln" #f #f 17 0 ((lionmove 2)))
(reverse-chariot "Reverse Chariot" "RC" whale #f 18 0 ((longmove 514)))
(side-mover "Side Mover" "SM" free-boar #f 19 0 ((shortmove 514) (longmove 80)))
(vertical-mover "Vertical Mover" "VM" flying-ox #f 20 0 ((shortmove 80) (longmove 514)))
(tokin "Tokin" "+P" #f #f 21 0 ((shortmove 599)))
(crown-prince "Crown Prince" "+DE" #f #f 22 0 ((shortmove 1879)))
(flying-stag "Flying Stag" "+BT" #f #f 23 0 ((shortmove 1365) (longmove 514)))
(flying-ox "Flying Ox" "+VM" #f #f 24 0 ((longmove 1799)))
(free-boar "Free Boar" "+SM" #f #f 25 0 ((longmove 1365)))
(horned-falcon "Horned Falcon" "+DH" #f #f 26 0 ((smalllionmove 2) (longmove 1877)))
(soaring-eagle "Soaring Eagle" "+DK" #f #f 27 0 ((smalllionmove 5) (longmove 1874)))
(whale "Whale" "+RC" #f #f 28 0 ((longmove 1794)))
(white-horse "White Horse" "+L" #f #f 29 0 ((longmove 519)))
(prom-silver-general "Promoted Silver General" "+S" #f #f 30 0 ((shortmove 80) (longmove 514)))
(prom-gold-general "Promoted Gold General" "+G" #f #f 31 0 ((longmove 594)))
(prom-copper-general "Promoted Copper General" "+C" #f #f 32 0 ((shortmove 514) (longmove 80)))
(prom-bishop "Promoted Bishop" "+B" #f #f 33 0 ((shortmove 594) (longmove 1285)))
(prom-rook "Promoted Rook" "+R" #f #f 34 0 ((shortmove 1285) (longmove 594)))
(prom-ferocious-leopard "Promoted Ferocious Leopard" "+FL" #f #f 35 0 ((longmove 1285)))
(prom-go-between "Promoted Go Between" "+GB" #f #f 36 0 ((shortmove 1367)))
)