((pawn "Pawn" "P" tokin #f 0 0 ((shortmove 2)))
(lance "Lance" "L" gold #f 1 0 ((longmove 2)))
(silver "Silver" "S" gold #f 2 0 ((shortmove 1287)))
(gold "Gold" "G" #f #f 3 0 ((shortmove 599)))
(copper "Copper" "C" gold #f 4 0 ((shortmove 519)))
(iron "Iron" "I" gold #f 5 0 ((shortmove 7)))
(dragon "Dragon" "FD" prom-dragon #f 6 0 ((longmove 1285)))
(sidemover "Sidemover" "SM" gold #f 7 0 ((longmove 80) (shortmove 514)))
(tiger "Tiger" "FT" gold #f 8 0 ((shortmove 1285)))
(chariot "Chariot" "FC" gold #f 9 0 ((longmove 514)))
(gobetween "Gobetween" "GB" gold #f 10 0 ((shortmove 514)))
(prom-dragon "Promoted Dragon" "+FD" #f #f 11 0 ((longmove 1285) (shortmove 594)))
(knight "Knight" "N" gold #f 12 0 ((knightmove 2)))
(king "King" "K" #f #f 13 0 ((shortmove 1911)))
(tokin "Tokin" "+P" #f pawn 14 0 ((shortmove 599)))
)