((pawn "Pawn" "P" knight #f 0 0 ((shortmove 2)))
(bishop "Bishop" "B" tokin #f 1 0 ((longmove 1285)))
(silver "Silver" "S" lance #f 2 0 ((shortmove 1287)))
(gold "Gold" "G" rook #f 3 0 ((shortmove 599)))
(knight "Knight" "N" #f pawn 4 0 ((knightmove 2)))
(tokin "Tokin" "+P" #f bishop 5 0 ((shortmove 599)))
(lance "Lance" "L" #f silver 6 0 ((longmove 2)))
(rook "Rook" "R" #f gold 7 0 ((longmove 594)))
(king "King" "K" #f #f 8 0 ((shortmove 1911)))
)