((pawn "Pawn" "P" tokin #f 0 0 ((shortmove 2)))
(king "King" "K" emperor #f 1 0 ((shortmove 1879)))
(lance "Lance" "L" prom-lance #f 2 0 ((longmove 2)))
(silver-general "Silver General" "S" free-silver #f 3 0 ((shortmove 1287)))
(gold-general "Gold General" "G" free-gold #f 4 0 ((shortmove 599)))
(copper-general "Copper General" "C" free-copper #f 5 0 ((shortmove 519)))
(bishop "Bishop" "B" prom-bishop #f 6 0 ((longmove 1285)))
(rook "Rook" "R" prom-rook #f 7 0 ((longmove 594)))
(angry-boar "Angry Boar" "AB" free-boar #f 8 0 ((shortmove 594)))
(dragon-horse "Dragon Horse" "DH" #f #f 9 0 ((shortmove 594) (longmove 1285)))
(dragon-king "Dragon King" "DK" #f #f 10 0 ((shortmove 1285) (longmove 594)))
(blind-bear "Blind Bear" "BB" free-bear #f 11 0 ((shortmove 1285) (longmove 512)))
(ferocious-leopard "Ferocious Leopard" "FL" free-leopard #f 12 0 ((shortmove 1799)))
(free-king "Free King" "FK" #f #f 13 0 ((longmove 1879)))
(blind-tiger "Blind Tiger" "BT" free-tiger #f 14 0 ((shortmove 1877)))
(kylin "Kylin" "Ky" great-dragon #f 15 0 ((shortmove 1285) (jumpmove 594)))
(phoenix "Phoenix" "Ph" golden-bird #f 16 0 ((shortmove 594) (jumpmove 1285)))
(lion "Lion" "Ln" furious-fiend #f 17 0 ((lionmove 2)))
(reverse-chariot "Reverse Chariot" "RC" prom-reverse-chariot #f 18 0 ((longmove 514)))
(side-mover "Side Mover" "SM" prom-side-mover #f 19 0 ((shortmove 514) (longmove 80)))
(vertical-mover "Vertical Mover" "VM" prom-vertical-mover #f 20 0 ((shortmove 80) (longmove 514)))
(buddhist-devil "Buddhist Devil" "BDe" prom-buddhist-devil #f 21 0 ((shortmove 592) (nummove 5 3)))
(cat-sword "Cat Sword" "CSw" free-cat #f 22 0 ((shortmove 1285)))
(capricorn "Capricorn" "Ca" prom-capricorn #f 23 0 ((diaghookmove 1285)))
(chinese-cock "Chinese Cock" "CC" wizard-stork #f 24 0 ((shortmove 597)))
(coiled-serpent "Coiled Serpent" "CS" free-serpent #f 25 0 ((shortmove 1794)))
(dark-spirit "Dark Spirit" "DSp" buddhist-spirit #f 26 0 ((shortmove 325)))
(evil-wolf "Evil Wolf" "EW" free-wolf #f 27 0 ((shortmove 87)))
(deva "Deva" "DV" teaching-king #f 28 0 ((shortmove 1045)))
(flying-dragon "Flying Dragon" "FD" prom-flying-dragon #f 29 0 ((nummove 1285 2)))
(donkey "Donkey" "Do" prom-donkey #f 30 0 ((shortmove 80) (jumpmove 514)))
(drunk-elephant "Drunk Elephant" "DE" prince #f 31 0 ((shortmove 1367)))
(earth-general "Earth General" "Ea" free-earth #f 32 0 ((shortmove 514)))
(go-between "Go Between" "GB" free-goer #f 33 0 ((shortmove 514)))
(guardian-of-the-gods "Guardian Of The Gods" "GG" prom-guardian-of-the-gods #f 34 0 ((shortmove 5) (nummove 594 3)))
(knight "Knight" "N" prom-knight #f 35 0 ((knightmove 2)))
(hook-mover "Hook Mover" "HM" prom-hook-mover #f 36 0 ((hookmove)))
(old-monkey "Old Monkey" "OM" mountain-witch #f 37 0 ((shortmove 1797)))
(iron-general "Iron General" "I" free-iron #f 38 0 ((shortmove 7)))
(left-chariot "Left Chariot" "LCh" prom-left-chariot #f 39 0 ((shortmove 512) (longmove 1027)))
(reclining-dragon "Reclining Dragon" "RD" free-dragon #f 40 0 ((shortmove 1874)))
(lion-dog "Lion Dog" "LD" prom-lion-dog #f 41 0 ((nummove 1879 3)))
(side-flyer "Side Flyer" "SF" prom-side-flyer #f 42 0 ((shortmove 1285) (longmove 80)))
(tile-general "Tile General" "T" free-tile #f 43 0 ((shortmove 517)))
(wrestler "Wrestler" "Wr" prom-wrestler #f 44 0 ((shortmove 80) (nummove 1285 3)))
(right-chariot "Right Chariot" "RCh" prom-right-chariot #f 45 0 ((shortmove 512) (longmove 262)))
(she-devil "She Devil" "SD" prom-she-devil #f 46 0 ((nummove 594 5) (nummove 1285 2)))
(stone-general "Stone General" "St" free-stone #f 47 0 ((shortmove 5)))
(violent-ox "Violent Ox" "VO" prom-violent-ox #f 48 0 ((nummove 594 2)))
(old-rat "Old Rat" "OR" bat #f 49 0 ((nummove 517 2)))
(furious-fiend "Furious Fiend" "FF" #f #f 50 0 ((nummove 1879 3) (lionmove 2)))
(bat "Bat" "Bt" #f #f 51 0 ((longmove 1282)))
(buddhist-spirit "Buddhist Spirit" "BSp" #f #f 52 0 ((longmove 1879) (lionmove 2)))
(emperor "Emperor" "E" #f #f 53 0 ((emperormove)))
(free-bear "Free Bear" "FBe" #f #f 54 0 ((jumpmove 5) (longmove 1365)))
(free-boar "Free Boar" "FBo" #f #f 55 0 ((longmove 1365)))
(free-cat "Free Cat" "FC" #f #f 56 0 ((longmove 1285)))
(free-copper "Free Copper" "FCo" #f #f 57 0 ((longmove 519)))
(free-dragon "Free Dragon" "FDr" #f #f 58 0 ((shortmove 1792) (longmove 7)))
(free-earth "Free Earth" "FEa" #f #f 59 0 ((longmove 514)))
(free-goer "Free Goer" "FG" #f #f 60 0 ((longmove 514)))
(free-gold "Free Gold" "FGo" #f #f 61 0 ((longmove 599)))
(free-iron "Free Iron" "FIr" #f #f 62 0 ((longmove 7)))
(free-leopard "Free Leopard" "FLp" #f #f 63 0 ((longmove 1799)))
(free-serpent "Free Serpent" "FSe" #f #f 64 0 ((longmove 1794)))
(free-silver "Free Silver" "FSi" #f #f 65 0 ((longmove 1287)))
(free-stone "Free Stone" "FSt" #f #f 66 0 ((longmove 5)))
(free-tiger "Free Tiger" "FT" #f #f 67 0 ((longmove 1877)))
(free-tile "Free Tile" "FTi" #f #f 68 0 ((longmove 517)))
(free-wolf "Free Wolf" "FW" #f #f 69 0 ((nummove 80 5) (longmove 1799)))
(golden-bird "Golden Bird" "GBd" #f #f 70 0 ((nummove 80 2) (nummove 1285 3) (longmove 514)))
(great-dragon "Great Dragon" "GD" #f #f 71 0 ((nummove 514 2) (nummove 1285 3) (longmove 80)))
(mountain-witch "Mountain Witch" "MW" #f #f 72 0 ((shortmove 2) (longmove 1797)))
(prince "Prince" "Pr" #f #f 73 0 ((shortmove 1879)))
(tokin "Tokin" "+P" #f #f 74 0 ((shortmove 599)))
(teaching-king "Teaching King" "TK" #f #f 75 0 ((longmove 1879)))
(teaching-king2 "Teaching King2" "TK" #f #f 75 0 ((longmove 1879) (lionmove 3)))
(wizard-stork "Wizard Stork" "WS" #f #f 76 0 ((shortmove 512) (longmove 1287)))
(prom-lance "Promoted Lance" "+L" #f #f 77 0 ((shortmove 599)))
(prom-bishop "Promoted Bishop" "+B" #f #f 78 0 ((shortmove 599)))
(prom-rook "Promoted Rook" "+R" #f #f 79 0 ((shortmove 599)))
(prom-reverse-chariot "Promoted Reverse Chariot" "+RC" #f #f 80 0 ((shortmove 599)))
(prom-side-mover "Promoted Side Mover" "+SM" #f #f 81 0 ((shortmove 599)))
(prom-vertical-mover "Promoted Vertical Mover" "+VM" #f #f 82 0 ((shortmove 599)))
(prom-buddhist-devil "Promoted Buddhist Devil" "+BDe" #f #f 83 0 ((shortmove 599)))
(prom-capricorn "Promoted Capricorn" "+Ca" #f #f 84 0 ((shortmove 599)))
(prom-flying-dragon "Promoted Flying Dragon" "+FD" #f #f 85 0 ((shortmove 599)))
(prom-donkey "Promoted Donkey" "+Do" #f #f 86 0 ((shortmove 599)))
(prom-guardian-of-the-gods "Promoted Guardian Of The Gods" "+GG" #f #f 87 0 ((shortmove 599)))
(prom-knight "Promoted Knight" "+N" #f #f 88 0 ((shortmove 599)))
(prom-hook-mover "Promoted Hook Mover" "+HM" #f #f 89 0 ((shortmove 599)))
(prom-left-chariot "Promoted Left Chariot" "+LCh" #f #f 90 0 ((shortmove 599)))
(prom-lion-dog "Promoted Lion Dog" "+LD" #f #f 91 0 ((shortmove 599)))
(prom-side-flyer "Promoted Side Flyer" "+SF" #f #f 92 0 ((shortmove 599)))
(prom-wrestler "Promoted Wrestler" "+Wr" #f #f 93 0 ((shortmove 599)))
(prom-right-chariot "Promoted Right Chariot" "+RCh" #f #f 94 0 ((shortmove 599)))
(prom-she-devil "Promoted She Devil" "+SD" #f #f 95 0 ((shortmove 599)))
(prom-violent-ox "Promoted Violent Ox" "+VO" #f #f 96 0 ((shortmove 599)))
)