((pawn "Pawn" "P" tokin #f 0 0 ((shortmove 2)))
(king "King" "K" #f #f 1 0 ((shortmove 1879)))
(lance "Lance" "L" gold-general #f 2 0 ((longmove 2)))
(knight "Knight" "N" gold-general #f 3 0 ((knightmove 2)))
(silver-general "Silver General" "S" gold-general #f 4 0 ((shortmove 1287)))
(gold-general "Gold General" "G" #f #f 5 0 ((shortmove 599)))
(bishop "Bishop" "B" dragon-horse #f 6 0 ((longmove 1285)))
(rook "Rook" "R" dragon-king #f 7 0 ((longmove 594)))
(dragon-horse "Dragon Horse" "+B" #f #f 8 0 ((shortmove 594) (longmove 1285)))
(dragon-king "Dragon King" "+R" #f #f 9 0 ((shortmove 1285) (longmove 594)))
(tokin "Tokin" "+P" #f #f 10 0 ((shortmove 599)))
(drunk-elephant "Drunk Elephant" "DE" crown-prince #f 11 0 ((shortmove 1367)))
(crown-prince "Crown Prince" "CP" #f #f 12 0 ((shortmove 1879)))
)