((pawn "Pawn" "P" tokin #f 0 0 ((shortmove 2)))
(king "King" "K" #f #f 1 4 ((shortmove 1879)))
(lance "Lance" "L" white-horse #f 2 0 ((longmove 2)))
(silver-general "Silver General" "S" prom-silver-general #f 3 0 ((shortmove 1287)))
(gold-general "Gold General" "G" prom-gold-general #f 4 0 ((shortmove 599)))
(copper-general "Copper General" "C" prom-copper-general #f 5 0 ((shortmove 519)))
(bishop "Bishop" "B" prom-bishop #f 6 0 ((longmove 1285)))
(rook "Rook" "R" prom-rook #f 7 0 ((longmove 594)))
(blind-tiger "Blind Tiger" "BT" flying-stag #f 8 0 ((shortmove 1877)))
(dragon-horse "Dragon Horse" "DH" prom-dragon-horse #f 9 0 ((shortmove 594) (longmove 1285)))
(dragon-king "Dragon King" "DK" prom-dragon-king #f 10 0 ((shortmove 1285) (longmove 594)))
(drunk-elephant "Drunk Elephant" "DE" crown-prince #f 11 0 ((shortmove 1367)))
(ferocious-leopard "Ferocious Leopard" "FL" prom-ferocious-leopard #f 12 0 ((shortmove 1799)))
(free-king "Free King" "FK" free-eagle #f 13 0 ((longmove 1879)))
(knight "Knight" "N" prom-knight #f 14 0 ((knightmove 2)))
(kylin "Kylin" "Ky" prom-kylin #f 15 0 ((shortmove 1285) (jumpmove 594)))
(phoenix "Phoenix" "Ph" prom-phoenix #f 16 0 ((shortmove 594) (jumpmove 1285)))
(lion "Lion" "Ln" lion-hawk #f 17 0 ((lionmove 2)))
(reverse-chariot "Reverse Chariot" "RC" whale #f 18 0 ((longmove 514)))
(side-mover "Side Mover" "SM" free-boar #f 19 0 ((shortmove 514) (longmove 80)))
(vertical-mover "Vertical Mover" "VM" flying-ox #f 20 0 ((shortmove 80) (longmove 514)))
(tokin "Tokin" "+P" #f #f 21 0 ((shortmove 599)))
(crown-prince "Crown Prince" "CP" #f #f 22 0 ((shortmove 1879)))
(flying-stag "Flying Stag" "FS" #f #f 23 0 ((shortmove 1365) (longmove 514)))
(flying-ox "Flying Ox" "FO" #f #f 24 0 ((longmove 1799)))
(free-boar "Free Boar" "FBo" #f #f 25 0 ((longmove 1365)))
(whale "Whale" "W" #f #f 26 0 ((longmove 1794)))
(white-horse "White Horse" "WH" #f #f 27 0 ((longmove 519)))
(dog "Dog" "Dg" multi-general #f 28 0 ((shortmove 1282)))
(free-eagle "Free Eagle" "FEg" #f #f 29 0 ((jumpmove 594) (longmove 1879)))
(horned-falcon "Horned Falcon" "HF" prom-horned-falcon #f 30 0 ((smalllionmove 2) (longmove 1877)))
(soaring-eagle "Soaring Eagle" "SE" prom-soaring-eagle #f 31 0 ((smalllionmove 5) (longmove 1874)))
(multi-general "Multi General" "MGn" #f #f 32 0 ((longmove 1282)))
(lion-hawk "Lion Hawk" "LHk" #f #f 33 0 ((longmove 1285) (areamove 2)))
(lion-hawk2 "Lion Hawk2" "LHk" #f #f 33 0 ((longmove 1285) (lionmove 2)))
(iron-general "Iron General" "I" prom-iron-general #f 34 0 ((shortmove 7)))
(chariot-soldier "Chariot Soldier" "ChS" heavenly-tetrarchs #f 35 0 ((nummove 80 2) (longmove 1799)))
(heavenly-tetrarchs "Heavenly Tetrarchs" "HT" #f #f 36 0 ((moveovermove 1285 100) (moveovermove 80 3) (iguimove)))
(water-buffalo "Water Buffalo" "WBf" fire-demon #f 37 0 ((nummove 514 2) (longmove 1365)))
(fire-demon "Fire Demon" "FiD" #f #f 38 0 ((longmove 1799) (areamove 3)))
(vertical-soldier "Vertical Soldier" "VSo" prom-vertical-soldier #f 39 0 ((shortmove 512) (nummove 80 2) (longmove 2)))
(side-soldier "Side Soldier" "SSo" prom-side-soldier #f 40 0 ((shortmove 512) (nummove 2 2) (longmove 80)))
(bishop-general "Bishop General" "BGn" vice-general #f 41 1 ((longmove 1285) (generalmove 1285 1)))
(vice-general "Vice General" "VGn" #f #f 42 2 ((longmove 1285) (generalmove 1285 2) (areamove 3)))
(rook-general "Rook General" "RGn" great-general #f 43 1 ((longmove 594) (generalmove 594 1)))
(great-general "Great General" "GGn" #f #f 44 3 ((longmove 1879) (generalmove 1879 3)))
(prom-silver-general "Promoted Silver General" "+S" #f #f 45 0 ((shortmove 80) (longmove 514)))
(prom-gold-general "Promoted Gold General" "+G" #f #f 46 0 ((longmove 594)))
(prom-copper-general "Promoted Copper General" "+C" #f #f 47 0 ((shortmove 514) (longmove 80)))
(prom-bishop "Promoted Bishop" "+B" #f #f 48 0 ((shortmove 594) (longmove 1285)))
(prom-rook "Promoted Rook" "+R" #f #f 49 0 ((shortmove 1285) (longmove 594)))
(prom-dragon-horse "Promoted Dragon Horse" "+DH" #f #f 50 0 ((smalllionmove 2) (longmove 1877)))
(prom-dragon-king "Promoted Dragon King" "+DK" #f #f 51 0 ((smalllionmove 5) (longmove 1874)))
(prom-ferocious-leopard "Promoted Ferocious Leopard" "+FL" #f #f 52 0 ((longmove 1285)))
(prom-knight "Promoted Knight" "+N" #f #f 53 0 ((shortmove 512) (nummove 2 2) (longmove 80)))
(prom-kylin "Promoted Kylin" "+Ky" #f #f 54 0 ((lionmove 2)))
(prom-phoenix "Promoted Phoenix" "+Ph" #f #f 55 0 ((longmove 1879)))
(prom-horned-falcon "Promoted Horned Falcon" "+HF" #f #f 56 1 ((longmove 1285) (generalmove 1285 1)))
(prom-soaring-eagle "Promoted Soaring Eagle" "+SE" #f #f 57 1 ((longmove 594) (generalmove 594 1)))
(prom-iron-general "Promoted Iron General" "+I" #f #f 58 0 ((shortmove 512) (nummove 80 2) (longmove 2)))
(prom-vertical-soldier "Promoted Vertical Soldier" "+VSo" #f #f 59 0 ((nummove 80 2) (longmove 1799)))
(prom-side-soldier "Promoted Side Soldier" "+SSo" #f #f 60 0 ((nummove 514 2) (longmove 1365)))
)