((dolphin "Dolphin" "D" dolphin2 #f 0 0 ((shortmove 2)))
(humpback "Humpback" "H" #f #f 1 0 ((shortmove 1797)))
(greywhale "Greywhale" "G" #f #f 2 0 ((longmove 1282)))
(bluewhale "Bluewhale" "B" #f #f 3 0 ((shortmove 519)))
(narwhal "Narwhal" "N" #f #f 4 0 ((shortmove 592) (jumpmove 2)))
(killerwhale "Killerwhale" "K" #f #f 5 0 ((longmove 594) (shortmove 1285)))
(dolphin2 "Dolphin2" "D" #f dolphin 6 0 ((longmove 1280)))
(porpoise "Porpoise" "P" #f killerwhale 7 0 ((shortmove 80)))
(whitewhale "Whitewhale" "W" #f #f 8 0 ((shortmove 1879)))
)