((pawn "Pawn" "P" ysilver #f 0 0 ((shortmove 2)))
(yrook "Yari Rook" "YR" rook #f 1 0 ((longmove 82)))
(ybishop "Yari Bishop" "YB" prom-ybishop #f 2 0 ((longmove 2) (shortmove 5)))
(yknight "Yari Knight" "YN" prom-yknight #f 3 0 ((longmove 2) (knightmove 2)))
(king "King" "K" #f #f 4 0 ((shortmove 1911)))
(rook "Rook" "+YR" #f yrook 5 0 ((longmove 594)))
(prom-ybishop "Promoted Yari Bishop" "+YB" #f ybishop 6 0 ((shortmove 87) (longmove 512)))
(prom-yknight "Promoted Yari Knight" "+YN" #f yknight 7 0 ((shortmove 87) (longmove 512)))
(ysilver "Yari Silver" "+P" #f pawn 8 0 ((shortmove 7) (longmove 512)))
)