extern ShortMove shortmove_1;
extern ShortMove shortmove_100;
extern ShortMove shortmove_145;
extern ShortMove shortmove_2;
extern ShortMove shortmove_200;
extern ShortMove shortmove_202;
extern ShortMove shortmove_205;
extern ShortMove shortmove_207;
extern ShortMove shortmove_250;
extern ShortMove shortmove_252;
extern ShortMove shortmove_255;
extern ShortMove shortmove_257;
extern ShortMove shortmove_4;
extern ShortMove shortmove_400;
extern ShortMove shortmove_415;
extern ShortMove shortmove_5;
extern ShortMove shortmove_50;
extern ShortMove shortmove_500;
extern ShortMove shortmove_502;
extern ShortMove shortmove_505;
extern ShortMove shortmove_507;
extern ShortMove shortmove_52;
extern ShortMove shortmove_55;
extern ShortMove shortmove_550;
extern ShortMove shortmove_555;
extern ShortMove shortmove_557;
extern ShortMove shortmove_57;
extern ShortMove shortmove_7;
extern ShortMove shortmove_700;
extern ShortMove shortmove_702;
extern ShortMove shortmove_705;
extern ShortMove shortmove_707;
extern ShortMove shortmove_717;
extern ShortMove shortmove_747;
extern ShortMove shortmove_752;
extern ShortMove shortmove_755;
extern ShortMove shortmove_757;
extern ShortMove shortmove_777;

extern LongMove longmove_102;
extern LongMove longmove_106;
extern LongMove longmove_2;
extern LongMove longmove_200;
extern LongMove longmove_202;
extern LongMove longmove_203;
extern LongMove longmove_205;
extern LongMove longmove_207;
extern LongMove longmove_252;
extern LongMove longmove_257;
extern LongMove longmove_402;
extern LongMove longmove_403;
extern LongMove longmove_5;
extern LongMove longmove_50;
extern LongMove longmove_500;
extern LongMove longmove_502;
extern LongMove longmove_505;
extern LongMove longmove_507;
extern LongMove longmove_52;
extern LongMove longmove_54;
extern LongMove longmove_555;
extern LongMove longmove_557;
extern LongMove longmove_7;
extern LongMove longmove_702;
extern LongMove longmove_705;
extern LongMove longmove_707;
extern LongMove longmove_752;
extern LongMove longmove_755;
extern LongMove longmove_757;

extern JumpMove jumpmove_2;
extern JumpMove jumpmove_202;
extern JumpMove jumpmove_205;
extern JumpMove jumpmove_252;
extern JumpMove jumpmove_5;
extern JumpMove jumpmove_502;
extern JumpMove jumpmove_505;
extern JumpMove jumpmove_707;

extern NumMove nummove_200_2;
extern NumMove nummove_202_2;
extern NumMove nummove_202_5;
extern NumMove nummove_205_2;
extern NumMove nummove_207_3;
extern NumMove nummove_252_2;
extern NumMove nummove_252_3;
extern NumMove nummove_252_5;
extern NumMove nummove_257_2;
extern NumMove nummove_2_2;
extern NumMove nummove_500_2;
extern NumMove nummove_505_2;
extern NumMove nummove_505_3;
extern NumMove nummove_505_5;
extern NumMove nummove_50_2;
extern NumMove nummove_50_5;
extern NumMove nummove_52_2;
extern NumMove nummove_550_5;
extern NumMove nummove_5_2;
extern NumMove nummove_5_3;
extern NumMove nummove_750_2;
extern NumMove nummove_752_2;
extern NumMove nummove_757_3;

extern KnightMove knightmove_2;
extern KnightMove knightmove_202;

extern AreaMove areamove_2;
extern AreaMove areamove_3;

extern DiaghookMove diaghookmove_5;
extern DiaghookMove diaghookmove_505;

extern HookMove hookmove;

extern MoveoverMove moveovermove_505_64;
extern MoveoverMove moveovermove_50_3;

extern IguiMove iguimove;

extern LionMove lionmove_2;
extern LionMove lionmove_3;

extern SmalllionMove smalllionmove_2;
extern SmalllionMove smalllionmove_5;

extern EmperorMove emperormove;

extern GeneralMove generalmove_252_1;
extern GeneralMove generalmove_505_1;
extern GeneralMove generalmove_505_2;
extern GeneralMove generalmove_757_3;

