ShortMove shortmove_1(0x1);
ShortMove shortmove_100(0x100);
ShortMove shortmove_145(0x145);
ShortMove shortmove_2(0x2);
ShortMove shortmove_200(0x200);
ShortMove shortmove_202(0x202);
ShortMove shortmove_205(0x205);
ShortMove shortmove_207(0x207);
ShortMove shortmove_250(0x250);
ShortMove shortmove_252(0x252);
ShortMove shortmove_255(0x255);
ShortMove shortmove_257(0x257);
ShortMove shortmove_4(0x4);
ShortMove shortmove_400(0x400);
ShortMove shortmove_415(0x415);
ShortMove shortmove_5(0x5);
ShortMove shortmove_50(0x50);
ShortMove shortmove_500(0x500);
ShortMove shortmove_502(0x502);
ShortMove shortmove_505(0x505);
ShortMove shortmove_507(0x507);
ShortMove shortmove_52(0x52);
ShortMove shortmove_55(0x55);
ShortMove shortmove_550(0x550);
ShortMove shortmove_555(0x555);
ShortMove shortmove_557(0x557);
ShortMove shortmove_57(0x57);
ShortMove shortmove_7(0x7);
ShortMove shortmove_700(0x700);
ShortMove shortmove_702(0x702);
ShortMove shortmove_705(0x705);
ShortMove shortmove_707(0x707);
ShortMove shortmove_717(0x717);
ShortMove shortmove_747(0x747);
ShortMove shortmove_752(0x752);
ShortMove shortmove_755(0x755);
ShortMove shortmove_757(0x757);
ShortMove shortmove_777(0x777);

LongMove longmove_102(0x102);
LongMove longmove_106(0x106);
LongMove longmove_2(0x2);
LongMove longmove_200(0x200);
LongMove longmove_202(0x202);
LongMove longmove_203(0x203);
LongMove longmove_205(0x205);
LongMove longmove_207(0x207);
LongMove longmove_252(0x252);
LongMove longmove_257(0x257);
LongMove longmove_402(0x402);
LongMove longmove_403(0x403);
LongMove longmove_5(0x5);
LongMove longmove_50(0x50);
LongMove longmove_500(0x500);
LongMove longmove_502(0x502);
LongMove longmove_505(0x505);
LongMove longmove_507(0x507);
LongMove longmove_52(0x52);
LongMove longmove_54(0x54);
LongMove longmove_555(0x555);
LongMove longmove_557(0x557);
LongMove longmove_7(0x7);
LongMove longmove_702(0x702);
LongMove longmove_705(0x705);
LongMove longmove_707(0x707);
LongMove longmove_752(0x752);
LongMove longmove_755(0x755);
LongMove longmove_757(0x757);

JumpMove jumpmove_2(0x2);
JumpMove jumpmove_202(0x202);
JumpMove jumpmove_205(0x205);
JumpMove jumpmove_252(0x252);
JumpMove jumpmove_5(0x5);
JumpMove jumpmove_502(0x502);
JumpMove jumpmove_505(0x505);
JumpMove jumpmove_707(0x707);

NumMove nummove_200_2(0x200, 0x2);
NumMove nummove_202_2(0x202, 0x2);
NumMove nummove_202_5(0x202, 0x5);
NumMove nummove_205_2(0x205, 0x2);
NumMove nummove_207_3(0x207, 0x3);
NumMove nummove_252_2(0x252, 0x2);
NumMove nummove_252_3(0x252, 0x3);
NumMove nummove_252_5(0x252, 0x5);
NumMove nummove_257_2(0x257, 0x2);
NumMove nummove_2_2(0x2, 0x2);
NumMove nummove_500_2(0x500, 0x2);
NumMove nummove_505_2(0x505, 0x2);
NumMove nummove_505_3(0x505, 0x3);
NumMove nummove_505_5(0x505, 0x5);
NumMove nummove_50_2(0x50, 0x2);
NumMove nummove_50_5(0x50, 0x5);
NumMove nummove_52_2(0x52, 0x2);
NumMove nummove_550_5(0x550, 0x5);
NumMove nummove_5_2(0x5, 0x2);
NumMove nummove_5_3(0x5, 0x3);
NumMove nummove_750_2(0x750, 0x2);
NumMove nummove_752_2(0x752, 0x2);
NumMove nummove_757_3(0x757, 0x3);

KnightMove knightmove_2(0x2);
KnightMove knightmove_202(0x202);

AreaMove areamove_2(0x2);
AreaMove areamove_3(0x3);

DiaghookMove diaghookmove_5(0x5);
DiaghookMove diaghookmove_505(0x505);

HookMove hookmove;

MoveoverMove moveovermove_505_64(0x505, 0x64);
MoveoverMove moveovermove_50_3(0x50, 0x3);

IguiMove iguimove;

LionMove lionmove_2(0x2);
LionMove lionmove_3(0x3);

SmalllionMove smalllionmove_2(0x2);
SmalllionMove smalllionmove_5(0x5);

EmperorMove emperormove;

GeneralMove generalmove_252_1(0x252, 0x1);
GeneralMove generalmove_505_1(0x505, 0x1);
GeneralMove generalmove_505_2(0x505, 0x2);
GeneralMove generalmove_757_3(0x757, 0x3);

